### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by nioerd** [conorpp/btproxy#13]
Unfortunately the program crashes at first run - error message below.

Traceback (most recent call last):
  File "/usr/local/bin/btproxy", line 4, in <module>
    __import__('pkg_resources').run_script('btproxy==0.1', 'btproxy')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/btproxy-0.1-py3.5-linux-x86_64.egg/EGG-INFO/scripts/btproxy", line 4, in <module>
    from libbtproxy.argparser import args,parser
  File "/usr/local/lib/python3.5/dist-packages/btproxy-0.1-py3.5-linux-x86_64.egg/libbtproxy/__init__.py", line 3, in <module>
    import clone
ImportError: /usr/local/lib/python3.5/dist-packages/btproxy-0.1-py3.5-linux-x86_64.egg/clone.cpython-35m-x86_64-linux-gnu.so: undefined symbol: Py_InitModule

How do I remove the program completely?
I tried the following ...

sudo python setup.py remove
sudo python setup.py uninstall
sudo python3 setup.py remove
sudo python3 setup.py uninstall

... did not work.

thanks in advance

**Comment by laksh225** [comment]
Use this
`python3 -m pip uninstall btproxy`
